quarkus.http.port=8084
quarkus.application.name=company-internal-documents-rag
quarkus.log.level=INFO

# Quarkus LangChain4J OpenAI Configuration (automatic EmbeddingModel bean)
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY:}
quarkus.langchain4j.openai.embedding-model.model-name=text-embedding-3-large

quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.driver=oracle.jdbc.driver.OracleDriver
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@localhost:1522/freepdb1
quarkus.datasource.username=vectordoc
quarkus.datasource.password=vectordoc
oracleai.embedding.table.name=document
oracleai.embedding.metadata.column=metadata

# Data to load on init
demo.data.load=true
demo.config.split.location=classpath:/config/document_splitting_rule.yaml
demo.config.access.location=classpath:/config/document_access_policy.yaml
demo.dir.location=classpath:/documents


# Document Chunking Configuration
document.chunking.default.strategy=recursive
document.chunking.default.chunk-size=300

# UI Configuration
ui.font.zoom.default=100
