services:
  company:
    extends:
      file: services/company-rag/docker-compose.yml
      service: oracle
    container_name: company
    ports:
      - "1522:1521"
  docling:
    extends:
      service: docling
      file: services/company-rag/docker-compose.yml
  ticket:
    extends:
      file: services/similar-tickets/docker-compose.yml
      service: oracle
    container_name: ticket
    ports:
      - "1521:1521"
  mysql:
    extends:
      service: mysql
      file: services/helpdesk/docker-compose.yml
volumes:
  mysql_data: