services:
  company:
    extends:
      file: services/medicalappointment-company-rag/docker-compose.yml
      service: oracle
    container_name: company
    ports:
      - "1522:1521"
  ticket:
    extends:
      file: services/medicalappointment-similar-tickets/docker-compose.yml
      service: oracle
    container_name: ticket
    ports:
      - "1521:1521"
  mysql:
    extends:
      service: mysql
      file: services/medicalappointment-helpdesk/docker-compose.yml
volumes:
  mysql_data: