package com.medicalappointment.ticketing.domain.enums;

public enum EventType {
    INCOMING_REQUEST_RECEIVED,
    DISPATCH_SUBMITTED,
    TICKET_CREATED,
    TICKET_ACCEPTED,
    TICKET_STATUS_CHANGED,
    TICKET_TYPE_CHANGED,
    TICKET_COMMENT_ADDED,
    RETURNED_TO_DISPATCH,
    SYSTEM_STEP,
    NOTIFICATION_SENT,
    ERROR_OCCURRED,
    AI_TICKET_CREATED,
    AI_TICKET_ROLLED_BACK,
    AI_TRIAGE_STARTED,
    AI_TRIAGE_RESULT,
    AI_TRIAGE_FAILED
}
