quarkus.http.port=8086
urgency.embedding-provider=local
urgency.model.dir=model
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY:}
quarkus.langchain4j.openai.embedding-model.model-name=text-embedding-3-small
