package com.example.appointment.service;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@ApplicationScoped
final class RepoManager {

    private final CommandRunner commandRunner;
    private final RepoPool pool = new RepoPool();

    @Inject
    RepoManager(CommandRunner commandRunner) {
        this.commandRunner = commandRunner;
    }

    RepoSlot acquire(
            String repoUrl,
            Path root,
            String baseBranch,
            Consumer<String> logger)
            throws IOException, InterruptedException {

        Files.createDirectories(root);

        RepoSlot slot;
        synchronized (pool) {
            slot = pool.acquire(root);
            slot.inUse = true;
        }

        try {
            if (!Files.exists(slot.path.resolve(".git"))) {
                commandRunner.runOrThrow(root, List.of("git", "clone", repoUrl, slot.id), "git clone", logger);
            }
            commandRunner.runOrThrow(slot.path, List.of("git", "checkout", baseBranch), "git checkout", logger);
            commandRunner.runOrThrow(slot.path, List.of("git", "fetch", "origin"), "git fetch", logger);
            commandRunner.runOrThrow(slot.path, List.of("git", "reset", "--hard", "origin/" + baseBranch), "git reset --hard", logger);
            commandRunner.runOrThrow(slot.path, List.of("git", "clean", "-fd"), "git clean -fd", logger);
            return slot;
        } catch (Exception e) {
            synchronized (pool) {
                slot.inUse = false;
            }
            throw e;
        }
    }

    String createFixBranch(Path repoDir, long ticketId, Consumer<String> logger)
            throws IOException, InterruptedException {
        String baseBranchName = "bugfix/ticket-" + ticketId;
        String branch = nextFreeBranchName(repoDir, baseBranchName);
        commandRunner.runOrThrow(repoDir, List.of("git", "checkout", "-B", branch), "create fix branch", logger);
        return branch;
    }

    private String nextFreeBranchName(Path repoDir, String baseBranchName) throws IOException, InterruptedException {
        Set<String> takenBranchNames = loadTakenBranchNames(repoDir, baseBranchName);
        if (!takenBranchNames.contains(baseBranchName)) {
            return baseBranchName;
        }
        int suffix = 2;
        while (takenBranchNames.contains(baseBranchName + "-" + suffix)) {
            suffix++;
        }
        return baseBranchName + "-" + suffix;
    }

    private Set<String> loadTakenBranchNames(Path repoDir, String baseBranchName) throws IOException, InterruptedException {
        CommandRunner.CommandResult branches = commandRunner.run(
                repoDir,
                List.of("git", "branch", "-a", "--format=%(refname:short)"),
                line -> {});
        Set<String> names = new HashSet<>();
        for (String raw : branches.stdoutLines()) {
            String name = raw == null ? "" : raw.trim();
            if (name.startsWith("remotes/origin/")) {
                name = name.substring("remotes/origin/".length());
            }
            if (name.startsWith("origin/")) {
                name = name.substring("origin/".length());
            }
            if (name.startsWith(baseBranchName)) {
                names.add(name);
            }
        }
        return names;
    }

    boolean hasWorkingTreeChanges(Path repoDir, Consumer<String> logger) throws IOException, InterruptedException {
        List<String> out = commandRunner.runOrThrow(repoDir, List.of("git", "status", "--porcelain"), "git status", logger);
        return !out.isEmpty();
    }

    String commitPushAndCreatePr(
            Path repoDir,
            String branch,
            long ticketId,
            String originalComplaint,
            String likelyCause,
            String fixSummary,
            double confidenceEstimate,
            Consumer<String> logger)
            throws IOException, InterruptedException {
        String commitMessage = "Fix ticket-" + ticketId + " based on AI Coding Assistant analysis";
        String prTitle = "AI fix for ticket-" + ticketId;
        String prBody = "Automated fix generated by AI coding-assistant.\n"
                + "\n**Original complaint:** " + valueOrEmpty(originalComplaint) + "\n"
                + "\n**Likely cause:** " + valueOrEmpty(likelyCause) + "\n"
                + "\n**Confidence estimate of bug cause:** " + confidenceEstimate + "\n"
                + "\n**Fix summary:** " + valueOrEmpty(fixSummary);

        commandRunner.runOrThrow(repoDir, List.of("git", "add", "."), "git add", logger);
        commandRunner.runOrThrow(repoDir, List.of("git", "commit", "-m", commitMessage), "git commit", logger);
        commandRunner.runOrThrow(repoDir, List.of("git", "push", "-u", "origin", branch), "git push", logger);

        List<String> prOut = commandRunner.runOrThrow(repoDir, List.of("gh", "pr", "create", "--title", prTitle, "--body", prBody), "gh pr create", logger);

        return prOut.stream()
                .filter(line -> line.startsWith("http://") || line.startsWith("https://"))
                .findFirst()
                .orElse("");
    }

    final class RepoSlot implements AutoCloseable {
        private final String id;
        private final Path path;
        private boolean inUse;

        private RepoSlot(String id, Path path) {
            this.id = id;
            this.path = path;
        }

        public Path path() {
            return path;
        }

        @Override
        public void close() {
            synchronized (pool) {
                inUse = false;
            }
        }
    }

    private final class RepoPool {
        private int nextId = 1;
        private final Map<String, RepoSlot> slots = new HashMap<>();

        RepoSlot acquire(Path root) {
            for (RepoSlot slot : slots.values()) {
                if (!slot.inUse) {
                    return slot;
                }
            }
            String id = "slot-" + nextId++;
            RepoSlot slot = new RepoSlot(id, root.resolve(id));
            slots.put(id, slot);
            return slot;
        }
    }

    private String valueOrEmpty(String value) {
        return value == null ? "" : value;
    }
}