server:
  port: 9090

urgency:
  provider: local
  providers:
    local:
      model:
        name: model-scorer-local.dnet
        location: ../urgency/model
      embedding:
        name: feature-hash-1536
        location: ../urgency/model/local-embeddings
        dimensions: 1536
    openai:
      model:
        name: model-scorer-openai.dnet
        location: ../urgency/model
      embedding:
        model:
          name: text-embedding-3-small
        dimensions: 1536

openai:
  api-key: ""
