quarkus.http.port=8084
%dev.quarkus.http.port=8084
quarkus.application.name=company-internal-documents-rag
quarkus.log.level=INFO

# Open API and Swagger UI config
quarkus.smallrye-openapi.info-title=Company Internal Documents API
%dev.quarkus.smallrye-openapi.info-title=Company Internal Documents API (development)
quarkus.smallrye-openapi.info-version=1.0.1
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=https://www.apache.org/licenses/LICENSE-2.0.html
quarkus.swagger-ui.enabled=true

# Quarkus LangChain4J OpenAI Configuration (automatic EmbeddingModel bean)
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY:}
quarkus.langchain4j.openai.embedding-model.model-name=text-embedding-3-large

quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.driver=oracle.jdbc.driver.OracleDriver
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@localhost:1522/freepdb1
quarkus.datasource.username=vector
quarkus.datasource.password=vector
oracleai.embedding.table.name=document
oracleai.embedding.metadata.column=metadata

# Data to load on init
demo.data.load=false
demo.config.split.location=classpath:/config/document_splitting_rule.yaml
demo.config.access.location=classpath:/config/document_access_policy.yaml
demo.dir.location=company-documents


# Document Chunking Configuration
document.chunking.default.strategy=recursive
document.chunking.default.chunk-size=300
document.preprocessing.mode=pure-text
document.preprocessing.docling.base-url=http://localhost:8086

# UI Configuration
ui.font.zoom.default=100
