quarkus.http.port=8081

# AI Triage Model Configuration
quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-mini
quarkus.langchain4j.openai.chat-model.temperature=0.2
quarkus.langchain4j.openai.chat-model.timeout=15s

# Similarity Service Configuration
quarkus.rest-client.similarity.url=http://localhost:8082
ai-triage.similarity.max-results=5
ai-triage.similarity.min-score=0.3

# Document Service Configuration
ai-triage.documents.max-results=5
ai-triage.documents.min-score=0.3
quarkus.rest-client.company-rag-documents.url=http://localhost:8084

# helpdesk
ai-triage.helpdesk.base-url=http://localhost:8080

# UI Configuration
ai-triage.ui.default-zoom-percent=100
ai-triage.ui.polling.enabled=true
ai-triage.ui.polling.interval-ms=2000

## Logging
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=0
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
