quarkus.application.name=MedicalAppointment
quarkus.application.version=1.0.0

# Server configuration
quarkus.http.port=8083
quarkus.http.test-port=9093


# Helpdesk integration
quarkus.rest-client.helpdesk-api.url=http://localhost:8080

# Qute template configuration
quarkus.qute.suffixes=html


## Logging
quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body-limit=0
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=INFO

