services:
  oracle:
    image: gvenzl/oracle-free:latest
    container_name: oracle-free
    restart: unless-stopped
    ports:
      - "1522:1521"
    environment:
      - ORACLE_PASSWORD=free
      - APP_USER_PASSWORD=vector
      - APP_USER=vector
  docling:
    image: quay.io/docling-project/docling-serve
    container_name: docling-serve
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - DOCLING_SERVE_ENABLE_UI=1
      - DOCLING_SERVE_ENABLE_REMOTE_SERVICES=true